feat: спринт 12 - готов!
DenniKs/java-filmorate pull request #4
Opened 2024-09-09 15:21 UTC by DenniKs

Добрый день!

2024-09-09 17:43 UTC, DenniKs commented
Добрый день!

После фиксов направляю работу на проверку по 12 спринту!

Спасибо!

2024-09-10 16:59 UTC, LexLippi requested changes
Привет!

Неплохая работа!

Есть некоторое количество замечаний, которые необходимо исправить!

Желаю удачи!

2024-09-10 16:59 UTC, LexLippi commented on src/main/resources/data.sql
> +ALTER TABLE LIKES ALTER COLUMN LIKE_ID RESTART WITH 1;
Этого в миграции быть не должно, так как ни один пользователь не захочет использовать приложение в котором при каждом релизе удаляются его данные, поэтому этого надо избегать

2024-09-10 16:59 UTC, LexLippi commented on src/main/resources/schema.sql
> +    EMAIL     VARCHAR(55) NOT NULL,
Согласно rfc допустимая длина адреса электронной почты доходит до 254 символов -- https://stackoverflow.com/questions/386294/what-is-the-maximum-length-of-a-valid-email-address

2024-09-10 16:59 UTC, LexLippi commented on src/main/resources/schema.sql
> +    FILM_ID INT NOT NULL,
Не хватает ограничения, которое запрещает пользователю дважды оставлять лайк к одному и тому же фильму

2024-09-10 16:59 UTC, LexLippi commented on src/main/resources/schema.sql
> +    FRIEND_ID     INT  NOT NULL,
Не хватает ограничения, которое запрещает более одного раза устанавливать дружбу между пользователями

2024-09-10 16:59 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/UserDbStorage.java
> +    }
Если метод не нужен, то он не должен быть задекларирован в интерфейсе, либо его нужно реализовать

2024-09-10 16:59 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/UserDbStorage.java
> +        return userOptional;
Вместо этого стоит использовать метод `.map()` или `.ifPresent` в зависимости от ситуации

2024-09-10 16:59 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/UserDbStorage.java
> +        User user;
Зачем здесь оюъявлять неинициализированную переменную?

2024-09-10 16:59 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/UserDbStorage.java
> +            }
Не стоит добавлять записи в цикле, стоит использовать `batchInsert`

2024-09-10 16:59 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/UserDbStorage.java
> +        boolean friendAccepted;
Зачем объявлять эту переменную заранее?
Почему нельзя объявить ее в момент инициализации?

2024-09-10 16:59 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/UserDbStorage.java
> +        User user;
`return` можно сделать в блоке `try` и объвлять неинициализированную переменную не придется

2024-09-10 16:59 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/controller/GenreController.java
> +    public Genre getGenreById(@PathVariable int id) {
А почему здесь в отличие от `FilmController` не `Optional` стоит придерживаться единой концепции везде. Лично мне ближе концепция везде возвращать объекты без оберток, но это на твое усмотрение :)

2024-09-10 16:59 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        for (Genre genre : film.getGenres()) {
Запросы в цикле это крайне неэффективно с точки зрения работы с СУБД
Здесь вполне можно обойтись одним запросом

2024-09-10 16:59 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        return film.orElse(null);
для того, чтобы это упростить у `Optional` есть такой замечательный метод, как `.orElseThrow()`

2024-09-10 16:59 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/GenreDbStorage.java
> +        return true;
Зачем тогда возвращать значение, если оно всегда одинаковое?

2024-09-10 16:59 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/GenreDbStorage.java
> +        return true;
Вопрос аналогичный тому, что ниже

2024-09-10 19:12 UTC, DenniKs commented
Добрый вечер

Внесены правки после ревью!

Спасибо!

2024-09-11 19:01 UTC, LexLippi commented
Привет!

Хорошая работа!

Желаю удачи в следующих спринтах!

2024-09-11 19:03 UTC, merged